/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 24
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_text = 1,
  anon_sym_GT = 2,
  anon_sym_LTgo_COLONimport = 3,
  anon_sym_LTgo_COLONendif = 4,
  anon_sym_LTgo_COLONendswitch = 5,
  anon_sym_LTgo_COLONendfor = 6,
  anon_sym_LTgo_COLONif = 7,
  anon_sym_LTgo_COLONelif = 8,
  anon_sym_LTgo_COLONelse = 9,
  anon_sym_LTgo_COLONswitch = 10,
  anon_sym_LTgo_COLONcase = 11,
  anon_sym_LTgo_COLONdefault = 12,
  anon_sym_LTgo_COLONfor = 13,
  anon_sym_LTgo_EQ = 14,
  sym_statement_start = 15,
  sym_go_code = 16,
  sym_html_open_tag = 17,
  sym_html_close_tag = 18,
  sym_html_self_closing_tag = 19,
  sym_html_comment = 20,
  sym_html_doctype = 21,
  sym_document = 22,
  sym__node = 23,
  sym_import_tag = 24,
  sym_import_start = 25,
  sym_close_tag = 26,
  sym_close_start = 27,
  sym_control_tag = 28,
  sym_control_start = 29,
  sym_echo_tag = 30,
  sym_echo_start = 31,
  sym_statement_tag = 32,
  aux_sym_document_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text] = "text",
  [anon_sym_GT] = ">",
  [anon_sym_LTgo_COLONimport] = "<go:import",
  [anon_sym_LTgo_COLONendif] = "<go:endif",
  [anon_sym_LTgo_COLONendswitch] = "<go:endswitch",
  [anon_sym_LTgo_COLONendfor] = "<go:endfor",
  [anon_sym_LTgo_COLONif] = "<go:if",
  [anon_sym_LTgo_COLONelif] = "<go:elif",
  [anon_sym_LTgo_COLONelse] = "<go:else",
  [anon_sym_LTgo_COLONswitch] = "<go:switch",
  [anon_sym_LTgo_COLONcase] = "<go:case",
  [anon_sym_LTgo_COLONdefault] = "<go:default",
  [anon_sym_LTgo_COLONfor] = "<go:for",
  [anon_sym_LTgo_EQ] = "<go=",
  [sym_statement_start] = "statement_start",
  [sym_go_code] = "go_code",
  [sym_html_open_tag] = "html_open_tag",
  [sym_html_close_tag] = "html_close_tag",
  [sym_html_self_closing_tag] = "html_self_closing_tag",
  [sym_html_comment] = "html_comment",
  [sym_html_doctype] = "html_doctype",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_import_tag] = "import_tag",
  [sym_import_start] = "import_start",
  [sym_close_tag] = "close_tag",
  [sym_close_start] = "close_start",
  [sym_control_tag] = "control_tag",
  [sym_control_start] = "control_start",
  [sym_echo_tag] = "echo_tag",
  [sym_echo_start] = "echo_start",
  [sym_statement_tag] = "statement_tag",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text] = sym_text,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LTgo_COLONimport] = anon_sym_LTgo_COLONimport,
  [anon_sym_LTgo_COLONendif] = anon_sym_LTgo_COLONendif,
  [anon_sym_LTgo_COLONendswitch] = anon_sym_LTgo_COLONendswitch,
  [anon_sym_LTgo_COLONendfor] = anon_sym_LTgo_COLONendfor,
  [anon_sym_LTgo_COLONif] = anon_sym_LTgo_COLONif,
  [anon_sym_LTgo_COLONelif] = anon_sym_LTgo_COLONelif,
  [anon_sym_LTgo_COLONelse] = anon_sym_LTgo_COLONelse,
  [anon_sym_LTgo_COLONswitch] = anon_sym_LTgo_COLONswitch,
  [anon_sym_LTgo_COLONcase] = anon_sym_LTgo_COLONcase,
  [anon_sym_LTgo_COLONdefault] = anon_sym_LTgo_COLONdefault,
  [anon_sym_LTgo_COLONfor] = anon_sym_LTgo_COLONfor,
  [anon_sym_LTgo_EQ] = anon_sym_LTgo_EQ,
  [sym_statement_start] = sym_statement_start,
  [sym_go_code] = sym_go_code,
  [sym_html_open_tag] = sym_html_open_tag,
  [sym_html_close_tag] = sym_html_close_tag,
  [sym_html_self_closing_tag] = sym_html_self_closing_tag,
  [sym_html_comment] = sym_html_comment,
  [sym_html_doctype] = sym_html_doctype,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_import_tag] = sym_import_tag,
  [sym_import_start] = sym_import_start,
  [sym_close_tag] = sym_close_tag,
  [sym_close_start] = sym_close_start,
  [sym_control_tag] = sym_control_tag,
  [sym_control_start] = sym_control_start,
  [sym_echo_tag] = sym_echo_tag,
  [sym_echo_start] = sym_echo_start,
  [sym_statement_tag] = sym_statement_tag,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONimport] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONendif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONendswitch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONendfor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONelif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONelse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONswitch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONcase] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONdefault] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONfor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_statement_start] = {
    .visible = true,
    .named = true,
  },
  [sym_go_code] = {
    .visible = true,
    .named = true,
  },
  [sym_html_open_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_close_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_html_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_import_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_import_start] = {
    .visible = true,
    .named = true,
  },
  [sym_close_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_close_start] = {
    .visible = true,
    .named = true,
  },
  [sym_control_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_control_start] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_start] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(61);
      if (lookahead == '<') ADVANCE(62);
      if (lookahead == '>') ADVANCE(64);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == 'D') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '>') ADVANCE(82);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '>') ADVANCE(79);
      if (lookahead == 'o') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '>') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '/', 77,
        ':', 25,
        '=', 76,
        '>', 79,
        0x0b, 9,
        '\f', 9,
        '\t', 77,
        '\n', 77,
        '\r', 77,
        ' ', 77,
      );
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == '>') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == '>') ADVANCE(79);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == '>') ADVANCE(81);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(64);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(81);
      END_STATE();
    case 16:
      if (lookahead == '>') ADVANCE(83);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == 'C') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'E') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'O') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'P') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'T') ADVANCE(22);
      END_STATE();
    case 22:
      if (lookahead == 'Y') ADVANCE(20);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(23);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(42);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 26:
      if (lookahead == 'c') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'c') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(36);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 32:
      if (lookahead == 'f') ADVANCE(69);
      if (lookahead == 'm') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 'f') ADVANCE(70);
      END_STATE();
    case 34:
      if (lookahead == 'f') ADVANCE(66);
      END_STATE();
    case 35:
      if (lookahead == 'f') ADVANCE(24);
      END_STATE();
    case 36:
      if (lookahead == 'f') ADVANCE(46);
      if (lookahead == 'i') ADVANCE(34);
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 37:
      if (lookahead == 'h') ADVANCE(72);
      END_STATE();
    case 38:
      if (lookahead == 'h') ADVANCE(67);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(33);
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(40);
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 47:
      if (lookahead == 'p') ADVANCE(45);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(68);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 51:
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 56:
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 57:
      if (lookahead == 'w') ADVANCE(39);
      END_STATE();
    case 58:
      if (lookahead == 'w') ADVANCE(41);
      END_STATE();
    case 59:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 60:
      if (eof) ADVANCE(61);
      if (lookahead == '<') ADVANCE(62);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '!') ADVANCE(1);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == 'g') ADVANCE(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONimport);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONendif);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONendswitch);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONendfor);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONif);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONelif);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONelse);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONswitch);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONcase);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONdefault);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONfor);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LTgo_EQ);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_statement_start);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_go_code);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_html_open_tag);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_html_close_tag);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_html_self_closing_tag);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_html_comment);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_html_doctype);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 60},
  [2] = {.lex_state = 60},
  [3] = {.lex_state = 60},
  [4] = {.lex_state = 60},
  [5] = {.lex_state = 60},
  [6] = {.lex_state = 60},
  [7] = {.lex_state = 60},
  [8] = {.lex_state = 60},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LTgo_COLONimport] = ACTIONS(1),
    [anon_sym_LTgo_COLONendif] = ACTIONS(1),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(1),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(1),
    [anon_sym_LTgo_COLONif] = ACTIONS(1),
    [anon_sym_LTgo_COLONelif] = ACTIONS(1),
    [anon_sym_LTgo_COLONelse] = ACTIONS(1),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(1),
    [anon_sym_LTgo_COLONcase] = ACTIONS(1),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(1),
    [anon_sym_LTgo_COLONfor] = ACTIONS(1),
    [anon_sym_LTgo_EQ] = ACTIONS(1),
    [sym_statement_start] = ACTIONS(1),
    [sym_html_open_tag] = ACTIONS(1),
    [sym_html_close_tag] = ACTIONS(1),
    [sym_html_self_closing_tag] = ACTIONS(1),
    [sym_html_comment] = ACTIONS(1),
    [sym_html_doctype] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(14),
    [sym__node] = STATE(2),
    [sym_import_tag] = STATE(2),
    [sym_import_start] = STATE(15),
    [sym_close_tag] = STATE(2),
    [sym_close_start] = STATE(16),
    [sym_control_tag] = STATE(2),
    [sym_control_start] = STATE(17),
    [sym_echo_tag] = STATE(2),
    [sym_echo_start] = STATE(18),
    [sym_statement_tag] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_text] = ACTIONS(5),
    [anon_sym_LTgo_COLONimport] = ACTIONS(7),
    [anon_sym_LTgo_COLONendif] = ACTIONS(9),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(9),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(9),
    [anon_sym_LTgo_COLONif] = ACTIONS(11),
    [anon_sym_LTgo_COLONelif] = ACTIONS(11),
    [anon_sym_LTgo_COLONelse] = ACTIONS(11),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(11),
    [anon_sym_LTgo_COLONcase] = ACTIONS(11),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(11),
    [anon_sym_LTgo_COLONfor] = ACTIONS(11),
    [anon_sym_LTgo_EQ] = ACTIONS(13),
    [sym_statement_start] = ACTIONS(15),
    [sym_html_open_tag] = ACTIONS(5),
    [sym_html_close_tag] = ACTIONS(17),
    [sym_html_self_closing_tag] = ACTIONS(5),
    [sym_html_comment] = ACTIONS(17),
    [sym_html_doctype] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym__node] = STATE(3),
    [sym_import_tag] = STATE(3),
    [sym_import_start] = STATE(15),
    [sym_close_tag] = STATE(3),
    [sym_close_start] = STATE(16),
    [sym_control_tag] = STATE(3),
    [sym_control_start] = STATE(17),
    [sym_echo_tag] = STATE(3),
    [sym_echo_start] = STATE(18),
    [sym_statement_tag] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_text] = ACTIONS(21),
    [anon_sym_LTgo_COLONimport] = ACTIONS(7),
    [anon_sym_LTgo_COLONendif] = ACTIONS(9),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(9),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(9),
    [anon_sym_LTgo_COLONif] = ACTIONS(11),
    [anon_sym_LTgo_COLONelif] = ACTIONS(11),
    [anon_sym_LTgo_COLONelse] = ACTIONS(11),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(11),
    [anon_sym_LTgo_COLONcase] = ACTIONS(11),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(11),
    [anon_sym_LTgo_COLONfor] = ACTIONS(11),
    [anon_sym_LTgo_EQ] = ACTIONS(13),
    [sym_statement_start] = ACTIONS(15),
    [sym_html_open_tag] = ACTIONS(21),
    [sym_html_close_tag] = ACTIONS(23),
    [sym_html_self_closing_tag] = ACTIONS(21),
    [sym_html_comment] = ACTIONS(23),
    [sym_html_doctype] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__node] = STATE(3),
    [sym_import_tag] = STATE(3),
    [sym_import_start] = STATE(15),
    [sym_close_tag] = STATE(3),
    [sym_close_start] = STATE(16),
    [sym_control_tag] = STATE(3),
    [sym_control_start] = STATE(17),
    [sym_echo_tag] = STATE(3),
    [sym_echo_start] = STATE(18),
    [sym_statement_tag] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_text] = ACTIONS(27),
    [anon_sym_LTgo_COLONimport] = ACTIONS(30),
    [anon_sym_LTgo_COLONendif] = ACTIONS(33),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(33),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(33),
    [anon_sym_LTgo_COLONif] = ACTIONS(36),
    [anon_sym_LTgo_COLONelif] = ACTIONS(36),
    [anon_sym_LTgo_COLONelse] = ACTIONS(36),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(36),
    [anon_sym_LTgo_COLONcase] = ACTIONS(36),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(36),
    [anon_sym_LTgo_COLONfor] = ACTIONS(36),
    [anon_sym_LTgo_EQ] = ACTIONS(39),
    [sym_statement_start] = ACTIONS(42),
    [sym_html_open_tag] = ACTIONS(27),
    [sym_html_close_tag] = ACTIONS(45),
    [sym_html_self_closing_tag] = ACTIONS(27),
    [sym_html_comment] = ACTIONS(45),
    [sym_html_doctype] = ACTIONS(45),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(48),
    [sym_text] = ACTIONS(50),
    [anon_sym_LTgo_COLONimport] = ACTIONS(48),
    [anon_sym_LTgo_COLONendif] = ACTIONS(48),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(48),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(48),
    [anon_sym_LTgo_COLONif] = ACTIONS(48),
    [anon_sym_LTgo_COLONelif] = ACTIONS(48),
    [anon_sym_LTgo_COLONelse] = ACTIONS(48),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(48),
    [anon_sym_LTgo_COLONcase] = ACTIONS(48),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(48),
    [anon_sym_LTgo_COLONfor] = ACTIONS(48),
    [anon_sym_LTgo_EQ] = ACTIONS(48),
    [sym_statement_start] = ACTIONS(48),
    [sym_html_open_tag] = ACTIONS(50),
    [sym_html_close_tag] = ACTIONS(48),
    [sym_html_self_closing_tag] = ACTIONS(50),
    [sym_html_comment] = ACTIONS(48),
    [sym_html_doctype] = ACTIONS(48),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(52),
    [sym_text] = ACTIONS(54),
    [anon_sym_LTgo_COLONimport] = ACTIONS(52),
    [anon_sym_LTgo_COLONendif] = ACTIONS(52),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(52),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(52),
    [anon_sym_LTgo_COLONif] = ACTIONS(52),
    [anon_sym_LTgo_COLONelif] = ACTIONS(52),
    [anon_sym_LTgo_COLONelse] = ACTIONS(52),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(52),
    [anon_sym_LTgo_COLONcase] = ACTIONS(52),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(52),
    [anon_sym_LTgo_COLONfor] = ACTIONS(52),
    [anon_sym_LTgo_EQ] = ACTIONS(52),
    [sym_statement_start] = ACTIONS(52),
    [sym_html_open_tag] = ACTIONS(54),
    [sym_html_close_tag] = ACTIONS(52),
    [sym_html_self_closing_tag] = ACTIONS(54),
    [sym_html_comment] = ACTIONS(52),
    [sym_html_doctype] = ACTIONS(52),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_text] = ACTIONS(58),
    [anon_sym_LTgo_COLONimport] = ACTIONS(56),
    [anon_sym_LTgo_COLONendif] = ACTIONS(56),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(56),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(56),
    [anon_sym_LTgo_COLONif] = ACTIONS(56),
    [anon_sym_LTgo_COLONelif] = ACTIONS(56),
    [anon_sym_LTgo_COLONelse] = ACTIONS(56),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(56),
    [anon_sym_LTgo_COLONcase] = ACTIONS(56),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(56),
    [anon_sym_LTgo_COLONfor] = ACTIONS(56),
    [anon_sym_LTgo_EQ] = ACTIONS(56),
    [sym_statement_start] = ACTIONS(56),
    [sym_html_open_tag] = ACTIONS(58),
    [sym_html_close_tag] = ACTIONS(56),
    [sym_html_self_closing_tag] = ACTIONS(58),
    [sym_html_comment] = ACTIONS(56),
    [sym_html_doctype] = ACTIONS(56),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(60),
    [sym_text] = ACTIONS(62),
    [anon_sym_LTgo_COLONimport] = ACTIONS(60),
    [anon_sym_LTgo_COLONendif] = ACTIONS(60),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(60),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(60),
    [anon_sym_LTgo_COLONif] = ACTIONS(60),
    [anon_sym_LTgo_COLONelif] = ACTIONS(60),
    [anon_sym_LTgo_COLONelse] = ACTIONS(60),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(60),
    [anon_sym_LTgo_COLONcase] = ACTIONS(60),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(60),
    [anon_sym_LTgo_COLONfor] = ACTIONS(60),
    [anon_sym_LTgo_EQ] = ACTIONS(60),
    [sym_statement_start] = ACTIONS(60),
    [sym_html_open_tag] = ACTIONS(62),
    [sym_html_close_tag] = ACTIONS(60),
    [sym_html_self_closing_tag] = ACTIONS(62),
    [sym_html_comment] = ACTIONS(60),
    [sym_html_doctype] = ACTIONS(60),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(64),
    [sym_text] = ACTIONS(66),
    [anon_sym_LTgo_COLONimport] = ACTIONS(64),
    [anon_sym_LTgo_COLONendif] = ACTIONS(64),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(64),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(64),
    [anon_sym_LTgo_COLONif] = ACTIONS(64),
    [anon_sym_LTgo_COLONelif] = ACTIONS(64),
    [anon_sym_LTgo_COLONelse] = ACTIONS(64),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(64),
    [anon_sym_LTgo_COLONcase] = ACTIONS(64),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(64),
    [anon_sym_LTgo_COLONfor] = ACTIONS(64),
    [anon_sym_LTgo_EQ] = ACTIONS(64),
    [sym_statement_start] = ACTIONS(64),
    [sym_html_open_tag] = ACTIONS(66),
    [sym_html_close_tag] = ACTIONS(64),
    [sym_html_self_closing_tag] = ACTIONS(66),
    [sym_html_comment] = ACTIONS(64),
    [sym_html_doctype] = ACTIONS(64),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(68), 1,
      sym_go_code,
  [4] = 1,
    ACTIONS(70), 1,
      sym_go_code,
  [8] = 1,
    ACTIONS(72), 1,
      sym_go_code,
  [12] = 1,
    ACTIONS(74), 1,
      sym_go_code,
  [16] = 1,
    ACTIONS(76), 1,
      sym_go_code,
  [20] = 1,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
  [24] = 1,
    ACTIONS(80), 1,
      sym_go_code,
  [28] = 1,
    ACTIONS(82), 1,
      sym_go_code,
  [32] = 1,
    ACTIONS(84), 1,
      sym_go_code,
  [36] = 1,
    ACTIONS(86), 1,
      sym_go_code,
  [40] = 1,
    ACTIONS(88), 1,
      anon_sym_GT,
  [44] = 1,
    ACTIONS(90), 1,
      anon_sym_GT,
  [48] = 1,
    ACTIONS(92), 1,
      anon_sym_GT,
  [52] = 1,
    ACTIONS(94), 1,
      anon_sym_GT,
  [56] = 1,
    ACTIONS(96), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 4,
  [SMALL_STATE(11)] = 8,
  [SMALL_STATE(12)] = 12,
  [SMALL_STATE(13)] = 16,
  [SMALL_STATE(14)] = 20,
  [SMALL_STATE(15)] = 24,
  [SMALL_STATE(16)] = 28,
  [SMALL_STATE(17)] = 32,
  [SMALL_STATE(18)] = 36,
  [SMALL_STATE(19)] = 40,
  [SMALL_STATE(20)] = 44,
  [SMALL_STATE(21)] = 48,
  [SMALL_STATE(22)] = 52,
  [SMALL_STATE(23)] = 56,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_tag, 3, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_tag, 3, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_tag, 3, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_tag, 3, 0, 1),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_tag, 3, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_close_tag, 3, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_tag, 3, 0, 1),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_control_tag, 3, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_tag, 3, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_tag, 3, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_start, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_start, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_start, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_start, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [78] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ghp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ghp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
