/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 22
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_text = 1,
  anon_sym_GT = 2,
  sym_import_start = 3,
  anon_sym_LTgo_COLONendif = 4,
  anon_sym_LTgo_COLONendswitch = 5,
  anon_sym_LTgo_COLONendfor = 6,
  anon_sym_LTgo_COLONif = 7,
  anon_sym_LTgo_COLONelif = 8,
  anon_sym_LTgo_COLONelse = 9,
  anon_sym_LTgo_COLONswitch = 10,
  anon_sym_LTgo_COLONcase = 11,
  anon_sym_LTgo_COLONdefault = 12,
  anon_sym_LTgo_COLONfor = 13,
  sym_echo_start = 14,
  sym_statement_start = 15,
  sym_go_code = 16,
  sym_document = 17,
  sym__node = 18,
  sym_import_tag = 19,
  sym_close_tag = 20,
  sym_close_start = 21,
  sym_control_tag = 22,
  sym_control_start = 23,
  sym_echo_tag = 24,
  sym_statement_tag = 25,
  aux_sym_document_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text] = "text",
  [anon_sym_GT] = ">",
  [sym_import_start] = "import_start",
  [anon_sym_LTgo_COLONendif] = "<go:endif",
  [anon_sym_LTgo_COLONendswitch] = "<go:endswitch",
  [anon_sym_LTgo_COLONendfor] = "<go:endfor",
  [anon_sym_LTgo_COLONif] = "<go:if",
  [anon_sym_LTgo_COLONelif] = "<go:elif",
  [anon_sym_LTgo_COLONelse] = "<go:else",
  [anon_sym_LTgo_COLONswitch] = "<go:switch",
  [anon_sym_LTgo_COLONcase] = "<go:case",
  [anon_sym_LTgo_COLONdefault] = "<go:default",
  [anon_sym_LTgo_COLONfor] = "<go:for",
  [sym_echo_start] = "echo_start",
  [sym_statement_start] = "statement_start",
  [sym_go_code] = "go_code",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_import_tag] = "import_tag",
  [sym_close_tag] = "close_tag",
  [sym_close_start] = "close_start",
  [sym_control_tag] = "control_tag",
  [sym_control_start] = "control_start",
  [sym_echo_tag] = "echo_tag",
  [sym_statement_tag] = "statement_tag",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text] = sym_text,
  [anon_sym_GT] = anon_sym_GT,
  [sym_import_start] = sym_import_start,
  [anon_sym_LTgo_COLONendif] = anon_sym_LTgo_COLONendif,
  [anon_sym_LTgo_COLONendswitch] = anon_sym_LTgo_COLONendswitch,
  [anon_sym_LTgo_COLONendfor] = anon_sym_LTgo_COLONendfor,
  [anon_sym_LTgo_COLONif] = anon_sym_LTgo_COLONif,
  [anon_sym_LTgo_COLONelif] = anon_sym_LTgo_COLONelif,
  [anon_sym_LTgo_COLONelse] = anon_sym_LTgo_COLONelse,
  [anon_sym_LTgo_COLONswitch] = anon_sym_LTgo_COLONswitch,
  [anon_sym_LTgo_COLONcase] = anon_sym_LTgo_COLONcase,
  [anon_sym_LTgo_COLONdefault] = anon_sym_LTgo_COLONdefault,
  [anon_sym_LTgo_COLONfor] = anon_sym_LTgo_COLONfor,
  [sym_echo_start] = sym_echo_start,
  [sym_statement_start] = sym_statement_start,
  [sym_go_code] = sym_go_code,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_import_tag] = sym_import_tag,
  [sym_close_tag] = sym_close_tag,
  [sym_close_start] = sym_close_start,
  [sym_control_tag] = sym_control_tag,
  [sym_control_start] = sym_control_start,
  [sym_echo_tag] = sym_echo_tag,
  [sym_statement_tag] = sym_statement_tag,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_import_start] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LTgo_COLONendif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONendswitch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONendfor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONelif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONelse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONswitch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONcase] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONdefault] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTgo_COLONfor] = {
    .visible = true,
    .named = false,
  },
  [sym_echo_start] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_start] = {
    .visible = true,
    .named = true,
  },
  [sym_go_code] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_import_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_close_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_close_start] = {
    .visible = true,
    .named = true,
  },
  [sym_control_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_control_start] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 1:
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '/') ADVANCE(57);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(44);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(3);
      if (lookahead == 'd') ADVANCE(9);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'f') ADVANCE(25);
      if (lookahead == 'i') ADVANCE(12);
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(49);
      if (lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(50);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(46);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(4);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(52);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(47);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(13);
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(20);
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(1);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(26);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 38:
      if (lookahead == 'w') ADVANCE(19);
      END_STATE();
    case 39:
      if (lookahead == 'w') ADVANCE(21);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'g') ADVANCE(24);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_import_start);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONendif);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONendswitch);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONendfor);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONif);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONelif);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONelse);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONswitch);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONcase);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONdefault);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LTgo_COLONfor);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_echo_start);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_statement_start);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_go_code);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(58);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 40},
  [2] = {.lex_state = 40},
  [3] = {.lex_state = 40},
  [4] = {.lex_state = 40},
  [5] = {.lex_state = 40},
  [6] = {.lex_state = 40},
  [7] = {.lex_state = 40},
  [8] = {.lex_state = 40},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_import_start] = ACTIONS(1),
    [anon_sym_LTgo_COLONendif] = ACTIONS(1),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(1),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(1),
    [anon_sym_LTgo_COLONif] = ACTIONS(1),
    [anon_sym_LTgo_COLONelif] = ACTIONS(1),
    [anon_sym_LTgo_COLONelse] = ACTIONS(1),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(1),
    [anon_sym_LTgo_COLONcase] = ACTIONS(1),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(1),
    [anon_sym_LTgo_COLONfor] = ACTIONS(1),
    [sym_echo_start] = ACTIONS(1),
    [sym_statement_start] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(14),
    [sym__node] = STATE(2),
    [sym_import_tag] = STATE(2),
    [sym_close_tag] = STATE(2),
    [sym_close_start] = STATE(15),
    [sym_control_tag] = STATE(2),
    [sym_control_start] = STATE(16),
    [sym_echo_tag] = STATE(2),
    [sym_statement_tag] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_text] = ACTIONS(5),
    [sym_import_start] = ACTIONS(7),
    [anon_sym_LTgo_COLONendif] = ACTIONS(9),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(9),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(9),
    [anon_sym_LTgo_COLONif] = ACTIONS(11),
    [anon_sym_LTgo_COLONelif] = ACTIONS(11),
    [anon_sym_LTgo_COLONelse] = ACTIONS(11),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(11),
    [anon_sym_LTgo_COLONcase] = ACTIONS(11),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(11),
    [anon_sym_LTgo_COLONfor] = ACTIONS(11),
    [sym_echo_start] = ACTIONS(13),
    [sym_statement_start] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__node] = STATE(3),
    [sym_import_tag] = STATE(3),
    [sym_close_tag] = STATE(3),
    [sym_close_start] = STATE(15),
    [sym_control_tag] = STATE(3),
    [sym_control_start] = STATE(16),
    [sym_echo_tag] = STATE(3),
    [sym_statement_tag] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_text] = ACTIONS(19),
    [sym_import_start] = ACTIONS(7),
    [anon_sym_LTgo_COLONendif] = ACTIONS(9),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(9),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(9),
    [anon_sym_LTgo_COLONif] = ACTIONS(11),
    [anon_sym_LTgo_COLONelif] = ACTIONS(11),
    [anon_sym_LTgo_COLONelse] = ACTIONS(11),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(11),
    [anon_sym_LTgo_COLONcase] = ACTIONS(11),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(11),
    [anon_sym_LTgo_COLONfor] = ACTIONS(11),
    [sym_echo_start] = ACTIONS(13),
    [sym_statement_start] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__node] = STATE(3),
    [sym_import_tag] = STATE(3),
    [sym_close_tag] = STATE(3),
    [sym_close_start] = STATE(15),
    [sym_control_tag] = STATE(3),
    [sym_control_start] = STATE(16),
    [sym_echo_tag] = STATE(3),
    [sym_statement_tag] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_text] = ACTIONS(23),
    [sym_import_start] = ACTIONS(26),
    [anon_sym_LTgo_COLONendif] = ACTIONS(29),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(29),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(29),
    [anon_sym_LTgo_COLONif] = ACTIONS(32),
    [anon_sym_LTgo_COLONelif] = ACTIONS(32),
    [anon_sym_LTgo_COLONelse] = ACTIONS(32),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(32),
    [anon_sym_LTgo_COLONcase] = ACTIONS(32),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(32),
    [anon_sym_LTgo_COLONfor] = ACTIONS(32),
    [sym_echo_start] = ACTIONS(35),
    [sym_statement_start] = ACTIONS(38),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_text] = ACTIONS(43),
    [sym_import_start] = ACTIONS(41),
    [anon_sym_LTgo_COLONendif] = ACTIONS(41),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(41),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(41),
    [anon_sym_LTgo_COLONif] = ACTIONS(41),
    [anon_sym_LTgo_COLONelif] = ACTIONS(41),
    [anon_sym_LTgo_COLONelse] = ACTIONS(41),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(41),
    [anon_sym_LTgo_COLONcase] = ACTIONS(41),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(41),
    [anon_sym_LTgo_COLONfor] = ACTIONS(41),
    [sym_echo_start] = ACTIONS(41),
    [sym_statement_start] = ACTIONS(41),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_text] = ACTIONS(47),
    [sym_import_start] = ACTIONS(45),
    [anon_sym_LTgo_COLONendif] = ACTIONS(45),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(45),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(45),
    [anon_sym_LTgo_COLONif] = ACTIONS(45),
    [anon_sym_LTgo_COLONelif] = ACTIONS(45),
    [anon_sym_LTgo_COLONelse] = ACTIONS(45),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(45),
    [anon_sym_LTgo_COLONcase] = ACTIONS(45),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(45),
    [anon_sym_LTgo_COLONfor] = ACTIONS(45),
    [sym_echo_start] = ACTIONS(45),
    [sym_statement_start] = ACTIONS(45),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_text] = ACTIONS(51),
    [sym_import_start] = ACTIONS(49),
    [anon_sym_LTgo_COLONendif] = ACTIONS(49),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(49),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(49),
    [anon_sym_LTgo_COLONif] = ACTIONS(49),
    [anon_sym_LTgo_COLONelif] = ACTIONS(49),
    [anon_sym_LTgo_COLONelse] = ACTIONS(49),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(49),
    [anon_sym_LTgo_COLONcase] = ACTIONS(49),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(49),
    [anon_sym_LTgo_COLONfor] = ACTIONS(49),
    [sym_echo_start] = ACTIONS(49),
    [sym_statement_start] = ACTIONS(49),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_text] = ACTIONS(55),
    [sym_import_start] = ACTIONS(53),
    [anon_sym_LTgo_COLONendif] = ACTIONS(53),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(53),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(53),
    [anon_sym_LTgo_COLONif] = ACTIONS(53),
    [anon_sym_LTgo_COLONelif] = ACTIONS(53),
    [anon_sym_LTgo_COLONelse] = ACTIONS(53),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(53),
    [anon_sym_LTgo_COLONcase] = ACTIONS(53),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(53),
    [anon_sym_LTgo_COLONfor] = ACTIONS(53),
    [sym_echo_start] = ACTIONS(53),
    [sym_statement_start] = ACTIONS(53),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_text] = ACTIONS(59),
    [sym_import_start] = ACTIONS(57),
    [anon_sym_LTgo_COLONendif] = ACTIONS(57),
    [anon_sym_LTgo_COLONendswitch] = ACTIONS(57),
    [anon_sym_LTgo_COLONendfor] = ACTIONS(57),
    [anon_sym_LTgo_COLONif] = ACTIONS(57),
    [anon_sym_LTgo_COLONelif] = ACTIONS(57),
    [anon_sym_LTgo_COLONelse] = ACTIONS(57),
    [anon_sym_LTgo_COLONswitch] = ACTIONS(57),
    [anon_sym_LTgo_COLONcase] = ACTIONS(57),
    [anon_sym_LTgo_COLONdefault] = ACTIONS(57),
    [anon_sym_LTgo_COLONfor] = ACTIONS(57),
    [sym_echo_start] = ACTIONS(57),
    [sym_statement_start] = ACTIONS(57),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(61), 1,
      sym_go_code,
  [4] = 1,
    ACTIONS(63), 1,
      sym_go_code,
  [8] = 1,
    ACTIONS(65), 1,
      sym_go_code,
  [12] = 1,
    ACTIONS(67), 1,
      sym_go_code,
  [16] = 1,
    ACTIONS(69), 1,
      sym_go_code,
  [20] = 1,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
  [24] = 1,
    ACTIONS(73), 1,
      sym_go_code,
  [28] = 1,
    ACTIONS(75), 1,
      sym_go_code,
  [32] = 1,
    ACTIONS(77), 1,
      anon_sym_GT,
  [36] = 1,
    ACTIONS(79), 1,
      anon_sym_GT,
  [40] = 1,
    ACTIONS(81), 1,
      anon_sym_GT,
  [44] = 1,
    ACTIONS(83), 1,
      anon_sym_GT,
  [48] = 1,
    ACTIONS(85), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 4,
  [SMALL_STATE(11)] = 8,
  [SMALL_STATE(12)] = 12,
  [SMALL_STATE(13)] = 16,
  [SMALL_STATE(14)] = 20,
  [SMALL_STATE(15)] = 24,
  [SMALL_STATE(16)] = 28,
  [SMALL_STATE(17)] = 32,
  [SMALL_STATE(18)] = 36,
  [SMALL_STATE(19)] = 40,
  [SMALL_STATE(20)] = 44,
  [SMALL_STATE(21)] = 48,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_tag, 3, 0, 1),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_tag, 3, 0, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_tag, 3, 0, 1),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_tag, 3, 0, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_tag, 3, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_tag, 3, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_tag, 3, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_close_tag, 3, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_tag, 3, 0, 1),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_control_tag, 3, 0, 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_start, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_start, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [71] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ghp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ghp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
